---
- name: Print Laptop'information
  vars:
    model: "T480s"
    country_name: "USA"
  hosts: centos
  tasks:
    - name: print laptop'model
      command: echo "My laptop'model is {{model}}"
      register: result

    - name: print country_name
      command: echo "i live {{model}}"
      register: result

    - name: show result on screen 
      debug: var=result.stdout_lines
