---
- name: Play 1
#  var:
#    laptop: "T480s"
  hosts: centos
  tasks:
    - name: print var car
      command:
        cmd: echo "car"
      register: result

    - name: show result on screen 
      debug: var=result.stdout_lines
