---
- name: Play testtttttttttttttttttttt
  hosts: centos
  tasks:
    - name: print var car
      ping:  
#      register: result

#    - name: show result on screen 
#      debug: var=result.stdout_lines
