---
- name: Play 1
  vars:
    laptop: "T480s"
  hosts: centos
  tasks:
    - name: print var laptop
      command:
        cmd: echo "{{laptop}}r"
      register: result

    - name: show result on screen 
      debug: var=result.stdout_lines
